workflows:
  sonarcloud:
    name: SonarCloud Workflow
    environment:
      vars:
        SONAR_TOKEN: SONAR_TOKEN # TOKEN gerado no sonar (criado nas variáveis do Codemagic)
    scripts:
      - name: Instalar o sonar-scanner no macOS
        script: |
          brew update
          brew install sonar-scanner
      - name: Executar análise no SonarCloud
        script: |
          sonar-scanner \
            -Dsonar.projectKey=viniciusnunes_api-teste \
            -Dsonar.organization=teste_alterar \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

