workflows:
  sonarcloud:
    name: SonarCloud Workflow
    environment:  
      vars:  
        SONAR_TOKEN: SONAR_TOKEN
    scripts:
      - name: Instalar o sonar-scanner no macOS
        script: |
          brew update
          brew install sonar-scanner
      - name: Verificar variável de ambiente
        script: |
          # Agora este echo deverá mostrar o prefixo do token,
          # confirmando que a variável está disponível.
          echo "Token começa com: ${SONAR_TOKEN:0:4}***"
      - name: Executar análise no SonarCloud
        script: |
          sonar-scanner \
            -Dsonar.projectKey=viniciusnunes_api-teste \
            -Dsonar.organization=teste_alterar \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
